### PR TITLE
[WIP] Build our own redis

### PR DESCRIPTION
**Pull request by cnelson**
This is temporarily submoduling our current redis image until we decide what to use for sentinel support at which time we'll replace it with something more approproiate

### CODE REVIEW

**Comment by rogeruiz** [comment]
@cnelson I've been testing this in k8s-dev with [this docker image](https://hub.docker.com/r/ausov/k8s-redis/). I haven't modified much, but I've forked it so I could test a few things out. wdyt about using that docker image rather than the one we currently use for our starting point?

**Comment by cnelson** [comment]
SGTM

**Comment by cnelson** [comment]
@rogeruiz can I close this PR?  Do you have your own branch with updated redis changes on it?

**Comment by rogeruiz** [comment]
@cnelson 
Yeah, I think it makes sense to close this. We could also just keep this in for now. I ended up using a different version of Redis for HA so we have a whole set of Dockerfiles for that in `redis-ha:customImages/redis32` (#55). Wdyt about upgrading all our Redis offerings to `3.x`?

**Comment by cnelson** [comment]
I think it's a good idea but one that is totally not in scope for a story that's already late :)

**Pull request closed without merging**
