### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by jontours**

### CODE REVIEW

**Comment by bengerman13** [comment]
@jontours is this still WIP, or ready, or abandoned?

**Comment by jontours** [comment]
@bengerman13 this is ready to review.  Sorry it's hard to review.  The makefile could maybe make use of `pushd` vs `cd`.

**Comment by bengerman13** [comment]
(not in this PR) we should stop vendoring dependencies here if at all possible

**Review by bengerman13 — APPROVED** [review]
Github won't let me review this in any meaningful way.
I've looked a the makefile, and I think it makes sense. I think you're right that `pushd` would be better than `cd`, but I'm more interested in having a practically-reviewable pr than making that improvement

**Pull request merged**
